/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import agentes.AgenteDetector;
import jade.gui.GuiEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import objetos.RecursosAprendizaje;

/**
 *
 * @author PalaHZ
 */
public class GUI_principal extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GUI_principal
     */
    private AgenteDetector agente;
    
    
    public GUI_principal() {
        initComponents();
    }

    public GUI_principal(AgenteDetector ag) {
        initComponents();
        this.agente = ag;
        this.jButtonBuscar.addActionListener(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jComboBoxRecursos = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 320, 160));

        jComboBoxRecursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxRecursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visual", "Lectura", "Auditivo", "Kinestesico" }));
        getContentPane().add(jComboBoxRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, 40));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_principal().setVisible(true);
            }
        });
    }
    
    public void establecerLista(ArrayList<RecursosAprendizaje> lista){
        String cadena = "";
        for (int i =0;i<lista.size();i++){
            cadena = String.format("%s \nNombre: %s\n%s\n%s\n%s\n\n",cadena,
                    lista.get(i).getTitulo_recurso(),
                    lista.get(i).getDetalle_recurso(),
                    lista.get(i).getEnlace_recurso(),
                    lista.get(i).getCategoria());
        }
        this.jTextArea.setText(cadena);
    }
    public void sinResultados(){
        this.jTextArea.setText("No se encontraron recursos");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxRecursos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        String categoria = this.jComboBoxRecursos.getSelectedItem().toString();
        GuiEvent ge = new GuiEvent(this, 1);
        ge.addParameter(categoria);
        agente.postGuiEvent(ge);
    }
}
